# Generated by Django 5.1.15 on 2026-08-25 03:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="Duration of the exam in minutes",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "pass_percentage",
                    models.PositiveIntegerField(
                        default=40,
                        help_text="Minimum percentage required to pass",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether students can see and attempt this exam.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"profile__role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("option_a", models.CharField(max_length=255, verbose_name="Option A")),
                ("option_b", models.CharField(max_length=255, verbose_name="Option B")),
                ("option_c", models.CharField(max_length=255, verbose_name="Option C")),
                ("option_d", models.CharField(max_length=255, verbose_name="Option D")),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[
                            ("A", "Option A"),
                            ("B", "Option B"),
                            ("C", "Option C"),
                            ("D", "Option D"),
                        ],
                        help_text="Select the correct option (A, B, C, or D)",
                        max_length=1,
                    ),
                ),
                (
                    "marks",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                    ),
                ),
            ],
        ),
    ]
